#!/usr/bin/env python3
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

from cli_parser import CLIParser, AnalyzerArgs
from analyzer import ChessAnalyzer


def main() -> None:
    try:
        args: AnalyzerArgs = CLIParser.parse_arguments()
        
        analyzer = ChessAnalyzer(args)
        analyzer.run()

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(84)


if __name__ == "__main__":
    main()